### ISSUE TITLE
Game won't start in Google Chrome

### ISSUE THREAD

**Issue by lhinderberger** [manniL/songmoji#3]
Unfortunately, the game won't start in Google Chrome. It displays the following error:

![image](https://user-images.githubusercontent.com/5623987/71324806-d3559980-24e3-11ea-88fd-a9b3886a8ec5.png)

This is in Google Chrome 79 on Windows 10.

**Comment by TheAlexLichter** [comment]
Probably a different implementation of the Gamepad API for Chrome/FF. Only tested the game in Firefox where the bug doesn't occur.

**Comment by TheAlexLichter** [comment]
Resolved in #5
